import os
import psycopg2
from datetime import datetime, date
import calendar

# DB Config
DB_TRAINING = {
    "dbname": "autonomous_training",
    "user": "{{DB_USER}}",
    "password": "{{GENERIC_API_SECRET}}",
    "host": "localhost",
    "port": "5432"
}

OUTPUT_DIR = "/home/{{USER}}/Documents/autonomous-living/docs/10_GOALS/G01_Target-Body-Fat/artifacts/reports"

def get_monthly_stats(year, month):
    stats = {}
    try:
        conn = psycopg2.connect(**DB_TRAINING)
        cur = conn.cursor()
        
        # 1. Workout Count
        cur.execute("""
            SELECT COUNT(*) FROM workouts 
            WHERE EXTRACT(YEAR FROM workout_date) = %s 
              AND EXTRACT(MONTH FROM workout_date) = %s
        """, (year, month))
        stats['workout_count'] = cur.fetchone()[0]
        
        # 2. Weight & BF Delta
        cur.execute("""
            SELECT measurement_date, bodyweight_kg, bodyfat_pct 
            FROM v_body_composition 
            WHERE EXTRACT(YEAR FROM measurement_date) = %s 
              AND EXTRACT(MONTH FROM measurement_date) = %s
            ORDER BY measurement_date ASC
        """, (year, month))
        rows = cur.fetchall()
        
        if rows:
            first = rows[0]
            last = rows[-1]
            stats['start_weight'] = float(first[1])
            stats['end_weight'] = float(last[1])
            stats['weight_delta'] = stats['end_weight'] - stats['start_weight']
            
            if first[2] and last[2]:
                stats['start_bf'] = float(first[2])
                stats['end_bf'] = float(last[2])
                stats['bf_delta'] = stats['end_bf'] - stats['start_bf']
            else:
                stats['bf_delta'] = 0
        
        # 3. Best HIT Volume (Average TUT)
        cur.execute("""
            SELECT AVG(tut_seconds) FROM workout_sets
            WHERE EXTRACT(YEAR FROM workout_date) = %s 
              AND EXTRACT(MONTH FROM workout_date) = %s
        """, (year, month))
        res = cur.fetchone()
        stats['avg_tut'] = float(res[0]) if res and res[0] else 0

        cur.close()
        conn.close()
    except Exception as e:
        print(f"DB Error: {e}")
    return stats

def generate_report():
    today = date.today()
    # We generate report for the current month (or specify if needed)
    year, month = today.year, today.month
    month_name = calendar.month_name[month]
    
    stats = get_monthly_stats(year, month)
    
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)
        
    filename = f"{year}-{month:02d}_Monthly_Health_Report.md"
    filepath = os.path.join(OUTPUT_DIR, filename)
    
    md = f"""---
title: "Health & Performance Report: {month_name} {year}"
type: "monthly_report"
goal_id: "goal-g01"
generated: "{datetime.now().strftime('%Y-%m-%d')}"
---

# 📈 Monthly Progress Summary: {month_name} {year}

## ⚖️ Body Composition
| Metric | Start | End | Delta |
|---|---|---|---|
| Weight (kg) | {stats.get('start_weight', 'N/A')} | {stats.get('end_weight', 'N/A')} | {stats.get('weight_delta', 0):+.1f} |
| Body Fat % | {stats.get('start_bf', 'N/A')}% | {stats.get('end_bf', 'N/A')}% | {stats.get('bf_delta', 0):+.1f}% |

## 💪 Training Performance (HIT)
- **Total Sessions:** {stats.get('workout_count', 0)}
- **Average Time Under Tension (TUT):** {stats.get('avg_tut', 0):.1f}s
- **Consistency Score:** {min(100, (stats.get('workout_count', 0) / 8) * 100):.0f}% (Target: 8 sessions/mo)

## 🎯 Insights
- **Weight Trend:** {'🔥 Losing' if stats.get('weight_delta', 0) < 0 else '📈 Gaining/Stable'}
- **Performance:** {'✅ Progressing' if stats.get('avg_tut', 0) > 60 else '⚠️ Focus on Intensity'}

---
*Report auto-generated by G01_monthly_reporter.py*
"""
    with open(filepath, 'w') as f:
        f.write(md)
    print(f"✅ Monthly report generated: {filepath}")

if __name__ == "__main__":
    generate_report()
