import os
import re
from datetime import datetime, timedelta

GOALS_PATH = "/home/{{USER}}/Documents/autonomous-living/docs/10_Goals"
OBSIDIAN_VAULT = "/home/{{USER}}/Documents/Obsidian Vault"
DAILY_NOTES_DIR = os.path.join(OBSIDIAN_VAULT, "01_Daily_Notes")

def get_recent_activities(days=7):
    """Scan all Activity-log.md files for entries within the last X days."""
    cutoff_date = datetime.now().date() - timedelta(days=days)
    recent_wins = []

    if not os.path.exists(GOALS_PATH):
        return []

    for goal_dir in sorted(os.listdir(GOALS_PATH)):
        if not goal_dir.startswith("G"): continue
        log_file = os.path.join(GOALS_PATH, goal_dir, "Activity-log.md")
        
        if os.path.exists(log_file):
            with open(log_file, 'r') as f:
                content = f.read()
                # Find ## YYYY-MM-DD
                entries = re.split(r"## (\d{4}-\d{2}-\d{2})", content)
                
                # entries[0] is header, entries[1] is first date, entries[2] is first content...
                for i in range(1, len(entries), 2):
                    date_str = entries[i]
                    entry_date = datetime.strptime(date_str, "%Y-%m-%d").date()
                    
                    if entry_date >= cutoff_date:
                        # Extract "Action:" line
                        action_match = re.search(r"\*\*Action:\*\*\s*(.+)", entries[i+1])
                        if action_match:
                            recent_wins.append({
                                "date": date_str,
                                "goal": goal_dir[:3],
                                "win": action_match.group(1).strip()
                            })
    return recent_wins

def get_obsidian_highlights(days=7):
    """Scan Obsidian notes for manually logged 'automation_win' and 'highlight' fields."""
    wins = []
    cutoff_date = datetime.now().date() - timedelta(days=days)
    
    for filename in sorted(os.listdir(DAILY_NOTES_DIR), reverse=True):
        if not filename.endswith(".md"): continue
        try:
            date_part = filename.replace(".md", "")
            file_date = datetime.strptime(date_part, "%Y-%m-%d").date()
            if file_date < cutoff_date: break
            
            with open(os.path.join(DAILY_NOTES_DIR, filename), 'r') as f:
                content = f.read()
                win_match = re.search(r"automation_win:\s*'(.+?)'", content)
                if win_match and win_match.group(1):
                    wins.append(f"[{date_part}] 🏆 WIN: {win_match.group(1)}")
                
                highlight_match = re.search(r"highlight:\s*'(.+?)'", content)
                if highlight_match and highlight_match.group(1):
                    wins.append(f"[{date_part}] ✨ HIGHLIGHT: {highlight_match.group(1)}")
        except:
            continue
    return wins

def draft_substack_post():
    activities = get_recent_activities()
    obsidian_wins = get_obsidian_highlights()
    
    now_str = datetime.now().strftime("%Y-W%U")
    filename = f"G02_Substack_Scout_Draft_{now_str}.md"
    filepath = os.path.join(GOALS_PATH, "G02_Automationbro-Recognition/data", filename)
    
    draft = f"""---
title: "Automationbro Update: {now_str}"
type: "substack_draft"
date: "{datetime.now().strftime('%Y-%m-%d')}"
---

# 🤖 Automationbro Weekly: Engineering the Autonomous Life ({now_str})

This week's engineering logs for the 2026 "Automation-First" North Star.

## 🏆 Key Wins from the Engineering Lab
"""
    # 1. Add Obsidian wins
    if obsidian_wins:
        for win in obsidian_wins:
            draft += f"- {win}
"
    
    # 2. Add Activity Log wins
    draft += "
## 📊 System Progress (Goal-by-Goal)
"
    for act in activities:
        draft += f"- **{act['goal']}**: {act['win']} ({act['date']})
"

    draft += """
## 🧠 The "Director's" Reflection
(Add your human insight here: What was the biggest bottleneck? What felt like magic?)

## 🚀 Next Milestone
- [ ] 
- [ ] 

---
*Draft auto-generated by G02 Substack Scout Agent.*
"""
    
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    with open(filepath, 'w') as f:
        f.write(draft)
    
    print(f"✅ Substack Draft created: {filepath}")
    return filepath

if __name__ == "__main__":
    draft_substack_post()
