import os
import re
from datetime import datetime, timedelta

# Paths
DOCS_DIR = "/home/{{USER}}/Documents/autonomous-living/docs"
GOALS_DIR = os.path.join(DOCS_DIR, "10_Goals")
OBSIDIAN_VAULT = "/home/{{USER}}/Documents/Obsidian Vault"
DAILY_NOTES_DIR = os.path.join(OBSIDIAN_VAULT, "01_Daily_Notes")
SUMMARIES_DIR = os.path.join(OBSIDIAN_VAULT, "02_Projects/Monthly Summaries")

def get_roadmap_stats():
    """Calculate task completion % for each goal's Q1 Roadmap."""
    stats = {}
    for goal in sorted(os.listdir(GOALS_DIR)):
        if not goal.startswith("G"): continue
        roadmap_path = os.path.join(GOALS_DIR, goal, "Roadmap.md")
        if os.path.exists(roadmap_path):
            with open(roadmap_path, 'r') as f:
                content = f.read()
                # Find Q1 section
                q1_match = re.search(r"## Q1(.*?)(?=
## Q2|\Z)", content, re.DOTALL)
                if q1_match:
                    tasks = re.findall(r"- \[([ xX])\]", q1_match.group(1))
                    if tasks:
                        done = tasks.count('x') + tasks.count('X')
                        total = len(tasks)
                        stats[goal[:3]] = {"done": done, "total": total, "pct": (done/total)*100, "name": goal[4:].replace("-", " ")}
    return stats

def get_monthly_accomplishments(month_str):
    """Aggregate 'Action' entries from all Activity-log.md files for the given month."""
    accomplishments = []
    for goal in sorted(os.listdir(GOALS_DIR)):
        if not goal.startswith("G"): continue
        log_path = os.path.join(GOALS_DIR, goal, "Activity-log.md")
        if os.path.exists(log_path):
            with open(log_path, 'r') as f:
                content = f.read()
                # Find entries for this month: ## YYYY-MM
                entries = re.split(r"## (\d{4}-\d{2}-\d{2})", content)
                for i in range(1, len(entries), 2):
                    if entries[i].startswith(month_str):
                        action_match = re.search(r"\*\*Action:\*\*\s*(.+)", entries[i+1])
                        if action_match:
                            accomplishments.append(f"- **{goal[:3]}**: {action_match.group(1).strip()} ({entries[i]})")
    return accomplishments

def generate_strategic_summary():
    now = datetime.now()
    month_str = now.strftime("%Y-%m")
    month_name = now.strftime("%B")
    
    roadmap_stats = get_roadmap_stats()
    accomplishments = get_monthly_accomplishments(month_str)
    
    filename = f"{month_str}-Progress-Summary-DRAFT.md"
    filepath = os.path.join(SUMMARIES_DIR, filename)
    
    md = f"""---
title: "2026 {month_name} Strategic Progress Summary"
type: "progress-summary"
status: "draft"
owner: "{{OWNER_NAME}}"
updated: "{now.strftime('%Y-%m-%d')}"
tags: ["{month_name} 2026", "Strategic Review", "Q1 Progress"]
---

# 2026 {month_name} Progress Summary

## 🎯 Q1 (Jan-Mar 2026) Progress Update

### Roadmap Completion Status
| Goal | Tasks Complete | Status |
|------|---------------|--------|
"""
    for gid, s in roadmap_stats.items():
        status_icon = "✅" if s['pct'] >= 50 else "🟡" if s['pct'] > 0 else "⚪"
        md += f"| **{gid}** {s['name']} | {s['done']}/{s['total']} | {s['pct']:.0f}% {status_icon} |
"

    md += "
## 📋 Major Accomplishments (Auto-Logged)
"
    if accomplishments:
        # Sort by date
        for acc in accomplishments[-15:]: # Take last 15 for the summary
            md += f"{acc}
"
    else:
        md += "No accomplishments logged this month.
"

    md += """
## 🧠 Key Insights & Discoveries
(Add your human insight here: What was the biggest bottleneck? What felt like magic?)

## 🛠️ Technical Achievements
- [x] Automated Google Tasks Sync for Pantry & House logistics
- [x] Implemented Smart Workout Logging (Pre-filled data)
- [x] Deployed Digital Twin Morning Mission Briefing
- [x] Enhanced Documentation Audit with traceability checks

## 🚀 Strategic Clarity Achieved
- **Foundation Status:** G04, G05, G10, G12 are maturing. 
- **Missing Data:** Health metrics (G01/G07) are pending hardware/API activation.

## 🏁 Conclusion
(Summarize the "vibe" of the month in one sentence.)

---
*Draft auto-generated by G11 Strategic Summarizer Agent.*
"""
    
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    with open(filepath, 'w') as f:
        f.write(md)
    
    print(f"✅ Strategic Summary Draft created: {filepath}")
    return filepath

if __name__ == "__main__":
    generate_strategic_summary()
